services:
  db:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    container_name: user_manage_mssql
    hostname: mssql_host
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -C -P ${MSSQL_PASSWORD} -Q 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 15
    volumes:
      - user_manage_db:/var/opt/mssql

  api1:
    build:
      context: ./api
      target: final
    ports:
      - "5001:8080"
    environment: &api_env
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - JwtConfig__Issuer=${JwtConfig__Issuer}
      - JwtConfig__Audience=${JwtConfig__Audience}
      - JwtConfig__Secret=${JwtConfig__Secret}
    depends_on:
      db:
        condition: service_healthy
        restart: true

  api2:
    build:
      context: ./api
      target: final
    ports:
      - "5002:8080"
    environment: *api_env
    depends_on:
      db:
        condition: service_healthy
        restart: true

  api3:
    build:
      context: ./api
      target: final
    ports:
      - "5003:8080"
    environment: *api_env
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  user_manage_db: