acl internal {
    192.168.1.0/24;
    172.17.0.0/16;
    172.18.0.0/16;
    172.19.0.0/16;
    172.20.0.0/16;
    172.21.0.0/16;  // <--- this one is used by docker
};

options {
    recursion yes;

    allow-query-cache { internal; };
    allow-query { internal; };

    forwarders {
        1.1.1.1;
        1.0.0.1;
    };
};

logging {
    channel query_logging {
        syslog daemon;
        severity debug 3;
        print-category yes;
    };

    category queries { query_logging; };
};